name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.11.9
  - pip<=24.0
  - pip:
      - mlflow==3.1.1
      - cloudpickle==3.1.1
      - numpy==1.26.4
      - pandas==2.2.2
      - scikit-learn==1.4.2
      - matplotlib==3.8.4
      - seaborn==0.13.2
