name: Workflow CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  train_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MLflow and dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow==3.1.1 scikit-learn pandas

      - name: Prepare dummy dataset
        working-directory: ./MLProject
        run: |
          mkdir -p data models
          echo "feature1,feature2,Personality" > personality_preprocessing_dataset.csv
          echo "1.0,2.0,0" >> personality_preprocessing_dataset.csv
          echo "2.0,3.0,1" >> personality_preprocessing_dataset.csv
          echo "3.0,4.0,0" >> personality_preprocessing_dataset.csv
          echo "4.0,5.0,1" >> personality_preprocessing_dataset.csv

      - name: Run MLflow project (training model)
        working-directory: ./MLProject
        run: |
          mlflow run . -e train --no-conda

      - name: Done
        run: echo "🎉 Workflow CI retraining selesai!"
