name: Workflow CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allows manual triggering

jobs:
  train_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Setting up job..."

      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          python --version
          pip --version
          env | sort

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn mlflow

      - name: Run mlflow project
        shell: bash -l {0}
        working-directory: ./MLProject
        run: |
          echo "feature1,feature2,Personality" > personality_preprocessing_dataset.csv
          echo "1.0,2.0,0" >> personality_preprocessing_dataset.csv
          echo "2.0,3.0,1" >> personality_preprocessing_dataset.csv
          echo "3.0,4.0,0" >> personality_preprocessing_dataset.csv
          echo "4.0,5.0,1" >> personality_preprocessing_dataset.csv

          # Run MLflow Project
          mlflow run . -e train -P data_path=personality_preprocessing_dataset.csv

      - name: Get latest MLflow run_id
        working-directory: ./MLProject
        run: |
          echo "RUN_ID=$(mlflow runs list -v | grep -v 'Run ID' | head -1 | awk '{print $4}')" >> $GITHUB_ENV
          echo "Latest MLflow run_id: ${{ env.RUN_ID }}"

      - name: Complete job
        run: echo "Workflow completed successfully!"
