name: Workflow CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  train_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Check mlflow version
        run: |
          which mlflow
          mlflow --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 scikit-learn pandas matplotlib seaborn

      - name: Run MLflow project
        working-directory: ./MLProject
        run: |
          mlflow run . \
            -e train \
            -P data_path=personality_preprocessing_dataset.csv \
            -P model_output=models/personality_model.pkl \
            -P test_size=0.2 \
            -P random_state=42 \
            --no-conda

      - name: Get latest MLflow run_id
        working-directory: ./MLProject
        run: |
          echo "RUN_ID=$(mlflow runs list -v | grep -v 'Run ID' | head -1 | awk '{print $4}')" >> $GITHUB_ENV
          echo "Latest MLflow run_id: ${{ env.RUN_ID }}"

      - name: Complete job
        run: echo "🎉 Workflow completed successfully!"
