name: CI MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLProject/personality_preprocessing_dataset.csv"
  TARGET_VAR: "Personality"
  TEST_SIZE: 0.2
  RANDOM_STATE: 42
  MODEL_OUTPUT: "models/personality_model.pkl"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # Cek variabel
      - name: Check Env
        run: |
          echo "CSV: $CSV_URL"
          echo "Target: $TARGET_VAR"

      # Install MLflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 pandas numpy scikit-learn joblib matplotlib seaborn

      # Jalankan MLflow Project
      - name: Run mlflow project
        run: |
          mlflow run MLProject \
            -P data_path=$CSV_URL \
            -P model_output=$MODEL_OUTPUT \
            -P test_size=$TEST_SIZE \
            -P random_state=$RANDOM_STATE \
            --env-manager=local
